stages:
  preprocess_data:
    cmd: python src/preprocess.py --config=params.yaml
    deps:
    - datasets/raw/chimi_text_dataset.csv
    - src/preprocess.py
    params:
    - base
    - data
    outs:
    - datasets/preprocessed/preprocessed_chimi_text_dataset
  train_model:
    cmd: python src/train.py --config=params.yaml
    deps:
    - models/base-spa-mt5
    - datasets/preprocessed/preprocessed_chimi_text_dataset
    - src/train.py
    params:
    - base
    - data
    - train
    outs:
    - reports/train
    - models/chimi-text-model
  evaluate_model:
    cmd: python src/eval.py --config=params.yaml
    deps:
    - models/chimi-text-model
    - datasets/preprocessed/preprocessed_chimi_text_dataset
    - src/eval.py
    params:
    - base
    - data
    - train
    metrics:
    - reports/eval/metrics.json:
        cache: false
params:
- reports/train/params.yaml
metrics:
- reports/train/metrics.json
plots:
- reports/train/plots/metrics:
    x: step
artifacts:
  best:
    path: reports/train/artifacts/best
    type: model
