stages:
  preprocess_data:
    cmd: python src/preprocess.py --config=params.yaml
    deps:
      - ${data.raw_dataset}
      - src/preprocess.py
    params:
      - base
      - data
    outs:
      - ${data.preprocessed_dataset}
  train_model:
    cmd: python src/train.py --config=params.yaml
    deps:
      - ${base.base_model_path}
      - ${data.preprocessed_dataset}
      - src/train.py
    params:
      - base
      - data
      - train
    outs:
      - ${train.trained_model_path}
    metrics:
      - ${train.reports_path}/metrics.json
    plots:
      - ${train.reports_path}/plots/metrics:
          x: step
  evaluate_model:
    cmd: python src/eval.py --config=params.yaml
    deps:
      - ${train.trained_model_path}
      - ${data.preprocessed_dataset}
      - src/eval.py
    params:
      - base
      - data
      - train
    metrics:
      - ${evaluate.metrics_path}
