base:
  seed: 42
  base_model_path: "models/base-spa-mt5"
data:
  raw_dataset: "datasets/raw/chimi_text_dataset.csv"
  preprocessed_dataset: "datasets/preprocessed/preprocessed_chimi_text_dataset"
  validation_and_test_size: 0.1
train:
  epochs: 1
  batch_size: 8
  trained_model_path: "models/chimi-text-model"
